
idx = 1;
x_length = 428;
y_length = 214;

for ix = 1:x_length
    for iy = 1:y_length

        neighbours(idx).label = sprintf('%s_%s', ix, iy);
        if ix == 1
            if iy == 1
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix+1, iy),...
                                               sprintf('%s_%s', ix, iy+1)}; %, ...
                                               % sprintf('%s_%s', ix+1, iy+1)};
            elseif iy == y_length
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix+1, iy),...
                                               sprintf('%s_%s', ix, iy-1)}; % , ...
                                               % sprintf('%s_%s', ix+1, iy-1)};

            else
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix+1, iy),...
                                               sprintf('%s_%s', ix, iy-1), ...
                                               sprintf('%s_%s', ix, iy+1)}; %, ...
                                               % sprintf('%s_%s', ix+1, iy-1), ...
                                               % sprintf('%s_%s', ix+1, iy+1)};

            end
        elseif ix == x_length
            if iy == 1
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix-1, iy),...
                                               sprintf('%s_%s', ix, iy+1)}; %, ...
                                               % sprintf('%s_%s', ix-1, iy+1)};
            elseif iy == y_length
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix-1, iy),...
                                               sprintf('%s_%s', ix, iy-1)}; %, ...
                                               % sprintf('%s_%s', ix-1, iy-1)};

            else
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix-1, iy),...
                                               sprintf('%s_%s', ix, iy-1), ...
                                               sprintf('%s_%s', ix, iy+1)}; %, ...
                                               % sprintf('%s_%s', ix-1, iy-1), ...
                                               % sprintf('%s_%s', ix-1, iy+1)};

            end
        else
            if iy == 1
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix-1, iy),...
                                               sprintf('%s_%s', ix, iy+1), ...
                                               sprintf('%s_%s', ix+1, iy)}; %, ...
                                               % sprintf('%s_%s', ix-1, iy+1), ...
                                               % sprintf('%s_%s', ix+1, iy+1)};
            elseif iy == y_length
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix-1, iy),...
                                               sprintf('%s_%s', ix, iy-1), ...
                                               sprintf('%s_%s', ix+1, iy)}; %, ...
                                               % sprintf('%s_%s', ix-1, iy-1), ...
                                               % sprintf('%s_%s', ix+1, iy-1)};
            else
                neighbours(idx).neighblabel = {sprintf('%s_%s', ix-1, iy),...
                                               sprintf('%s_%s', ix+1, iy),...
                                               sprintf('%s_%s', ix, iy-1), ...
                                               sprintf('%s_%s', ix, iy+1)}; %, ...
                                               % sprintf('%s_%s', ix-1, iy-1), ...
                                               % sprintf('%s_%s', ix-1, iy+1), ...
                                               % sprintf('%s_%s', ix+1, iy-1), ...
                                               % sprintf('%s_%s', ix+1, iy+1)};

            end
        end

    idx = idx + 1;
    end
end

save('immediate_neighbours_rectangle.mat', 'neighbours')




